name: Java JUnit5 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java Code
        run: javac -cp .:junit-platform-console-standalone-1.10.0.jar $(find src -name "*.java")

      - name: Run Tests
        run: |
          java -jar junit-platform-console-standalone-1.10.0.jar \
            --classpath src \
            --scan-class-path
